### ISSUE TITLE
为什么无法上传文件夹

### ISSUE THREAD

**Issue by LiuHH2018** [LiuHH2018/python_study#1]
试图上传文件夹到github repository，但是提示your branch is up to date

**Comment by JKChang2015** [comment]
通常情况下，github不会上传空的文件夹，所以在创建文件夹后，记得在里面添加文件

**Comment by JKChang2015** [comment]
https://github.com/LiuHH2018/python_study/blame/master/Daily%20notes/001_数据同步在线.md#L17

添加文件夹时，确保里面有文件

**Comment by LiuHH2018** [comment]
妥~~
